name: 'Stack to deploy dotnet application to azure'

on:
  workflow_dispatch
  
jobs:
  setup: 
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
